# Generated by Django 5.0.1 on 2024-02-22 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('availability', models.BooleanField(default=True)),
                ('condition', models.CharField(default='', max_length=100)),
                ('price_per_day', models.FloatField(default=0.0, max_length=1000)),
                ('images', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('location', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='airfinn.user')),
            ],
        ),
    ]
