# Generated by Django 5.0.1 on 2024-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airfinn', '0002_item_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='postal_code',
            field=models.CharField(max_length=4),
        ),
    ]
