# Generated by Django 5.0.1 on 2024-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airfinn', '0003_alter_item_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(default='https://rentopia-images.dybedahlserver.net/default_profile_picture.jpg'),
        ),
    ]
