# Generated by Django 5.0.1 on 2024-02-20 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airfinn', '0005_item_availability_item_category_item_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='airfinn.user'),
        ),
    ]
