# Generated by Django 4.2.11 on 2024-05-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airfinn', '0008_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='period',
        ),
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
