# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: VUE App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TMPDIR: /home/runner/tmp  # Specify the temporary directory path
    
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
      
    - name: Install dependencies
      working-directory: ./vue-app
      run: npm ci

    - name: Run tests
      working-directory: ./vue-app
      run: npm run test:unit
    
    - name: Lint
      working-directory: ./vue-app
      run: npm run lint
    
    - name: Build
      working-directory: ./vue-app
      run: npm run test:build -- --dest $TMPDIR/build
    
    # Clean up the temporary directory after testing
    - name: Clean up temporary directory
      run: rm -rf $TMPDIR/build
